// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUUbsnm6M6OY0hvSM6DUawwOZ2f8AA5mg',
    appId: '1:983323681328:web:207c789f4651ba83f9c3f5',
    messagingSenderId: '983323681328',
    projectId: 'tezda-assignment',
    authDomain: 'tezda-assignment.firebaseapp.com',
    storageBucket: 'tezda-assignment.appspot.com',
    measurementId: 'G-R0HMY0HQ1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwX4Gl1BBoI1Dd6YKL2CTzJuMWCCtYqCo',
    appId: '1:983323681328:android:892622c878b75c1ff9c3f5',
    messagingSenderId: '983323681328',
    projectId: 'tezda-assignment',
    storageBucket: 'tezda-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7PfjTxEzgDT5ih-ea5lCFQXNHnXWjjLs',
    appId: '1:983323681328:ios:8b7d4e0193a44574f9c3f5',
    messagingSenderId: '983323681328',
    projectId: 'tezda-assignment',
    storageBucket: 'tezda-assignment.appspot.com',
    iosBundleId: 'com.example.tezdaAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7PfjTxEzgDT5ih-ea5lCFQXNHnXWjjLs',
    appId: '1:983323681328:ios:8b7d4e0193a44574f9c3f5',
    messagingSenderId: '983323681328',
    projectId: 'tezda-assignment',
    storageBucket: 'tezda-assignment.appspot.com',
    iosBundleId: 'com.example.tezdaAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUUbsnm6M6OY0hvSM6DUawwOZ2f8AA5mg',
    appId: '1:983323681328:web:ceb85c6084a3c59ff9c3f5',
    messagingSenderId: '983323681328',
    projectId: 'tezda-assignment',
    authDomain: 'tezda-assignment.firebaseapp.com',
    storageBucket: 'tezda-assignment.appspot.com',
    measurementId: 'G-98SEZFYQ31',
  );
}
